### ISSUE TITLE
Feature requests: !processing !arduino, !mbot, !dojo, !damster_dojo and !gitlab

### ISSUE THREAD

**Issue by richelbilderbeek** [daantje1/djogbot#1]
I have a feature request:

If the user types `!processing` he/she should be taken to [https://github.com/richelbilderbeek/processing_voor_jonge_tieners/blob/master/hoofdstukken/README.md#leskaart-1-graphics](https://github.com/richelbilderbeek/processing_voor_jonge_tieners/blob/master/hoofdstukken/README.md#leskaart-1-graphics).

If the user types `!arduino` he/she should be taken to [https://github.com/richelbilderbeek/arduino_voor_jonge_tieners/tree/v1_0/hoofdstukken#lessen](https://github.com/richelbilderbeek/arduino_voor_jonge_tieners/tree/v1_0/hoofdstukken#lessen).

If the user types `!mbot` he/she should be taken to [https://github.com/richelbilderbeek/mbot_voor_jonge_tieners/tree/master/hoofdstukken#hoofdstukken](https://github.com/richelbilderbeek/mbot_voor_jonge_tieners/tree/master/hoofdstukken#hoofdstukken).

If the user types `!dojo` he/she should be taken to [https://github.com/djog/dojo#dojo](https://github.com/djog/dojo#dojo).

If the user types `!damster_dojo` he/she should be taken to [https://github.com/djog/damster_dojo#damster-dojo](https://github.com/djog/damster_dojo#damster-dojo).

If the user types `!gitlab` he/she should be taken to [http://51.15.53.32/users/sign_in](http://51.15.53.32/users/sign_in).

Looks doable to me. Can and will you do this?

**Comment by daantje1** [comment]
Thanks, i will work on it

**Comment by daantje1** [comment]
1

**Comment by daantje1** [comment]
Done
