### ISSUE TITLE
Joshua collaborator maken

### ISSUE THREAD

**Issue by richelbilderbeek** [daantje1/djogbot#10]
Hoi Daan, 

ik wil graag Joshua, oftewel, @Joshua260403 ook Collaborator maken. Zou jij dat kunnen doen? 

Joshua heeft de Dyno bot op Discord gezet en hij is ook handig op Discord.

Dankjewel en groetjes, Richel

**Comment by daantje1** [comment]
oke, ga ik nu regelen
