### ISSUE TITLE
Getimede berichten

### ISSUE THREAD

**Issue by richelbilderbeek** [daantje1/djogbot#9]
Hoi @daantje1, kan de djogbot ook getimede berichten? Zo ja, dan zou ik graag onderstaande getimede berichten willen.

Je ziet daar ook dat ik donderdag twee groepen heb. Ik weet niet hoe ik dat goed op Discord in kan richten. Als jij ideen hebt, hoor ik het graag :+1:

## Voor Appingedam/Damster Dojo

 * Maandag 18:00: `Welkom Damsters!`
 * Maandag 18:15: `3, 2, 1, de les begint!`
 * Maandag 19:00: `3, 2, 1, pauze!`
 * Maandag 19:15: `3, 2, 1, de les begint weer!`
 * Maandag 20:00: `3, 2, 1, les is voorbij!`

## Voor Groningen/Dojo Nano's

 * Donderdag 18:15: `@nanos: Welkom Grunninger!`
 * Donderdag 18:30: `@nanos: 3, 2, 1, de les begint!`
 * Donderdag 19:15: `@nanos: 3, 2, 1, pauze!`
 * Donderdag 19:30: `@nanos: 3, 2, 1, de les begint weer!`
 * Donderdag 20:00: `@nanos: 3, 2, 1, les is voorbij!`

## Voor Groningen/Dojo Uno's

 * Donderdag 19:00: `@unos: Welkom Grunninger!`
 * Donderdag 19:15: `@unos: 3, 2, 1, de les begint!`
 * Donderdag 20:00: `@unos: 3, 2, 1, pauze!`
 * Donderdag 20:15: `@unos: 3, 2, 1, de les begint weer!`
 * Donderdag 21:00: `@unos: 3, 2, 1, les is voorbij! Of het is pauze, als je nog door wil gaan :sunglasses:`
 * Donderdag 21:15: `@unos: 3, 2, 1, de les begint weer weer!` (ja, dit is een grapje!)
 * Donderdag 22:00: `@unos: 3, 2, 1, les is voorbij! `

**Comment by daantje1** [comment]
ja zou misschien kunnen, weet ik niet zeker, ga even onderzoek doen

**Comment by richelbilderbeek** [comment]
En, gelukt? Ik her-open de Issue, omdat dit volgens mij nog niet gelukt is :+1:

**Comment by richelbilderbeek** [comment]
Het is prima zonder bots :+1:
